name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-north-east-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build tag push to AWS ECR
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hustle
        IMAGE_TAG: latest
      run: |
        docker build ./Weather.API/ --file Dockerfile --tag my-image-name:$(date +%s)
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

