# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    #if: github.repository == 'octo-org/octo-repo-prod'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Name of the branch
      run: echo "Branch name is ${{ github.ref_name }}"
    - name: Match Branch name
      id: match-branch-name
      run: |
         if [[ ${{ github.ref_name }} =~ ^release.[0-9]+.[0-9]+$ ]]; then
             echo ::set-output name=match-branch-name::true
         fi
    - name: Set variables if branch match
      id: build-variables
      if: steps.check-tag.outputs.match-branch-name == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const data = ref.split('.')
          console.log(data, ref)
      run: |
        echo "Branch name is a match"   
    
