# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch: 
    
jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    env:
      ECS_PATH: 'ecs/'
      MAIN_IMAGE_LINK: ${{ secrets.MAIN_IMAGE_LINK }}


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
        working-directory: ${{ env.ECS_PATH }}
      - run: npm run build --if-present
        working-directory: ${{ env.ECS_PATH }}
      - run: npm test
        working-directory: ${{ env.ECS_PATH }}
      - name: Install CDK
        run: npm install -g aws-cdk
        working-directory: ${{ env.ECS_PATH }}
      - run: ls
      - name: CDK run
        run: cdk synth
      - run: cdk deploy        
